<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
    <PackageVersion Include="AutoMapper" Version="12.0.1" />
    <PackageVersion Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageVersion Include="MailKit" Version="4.14.1" />
    <PackageVersion Include="MassTransit.EntityFrameworkCore" Version="8.5.8-develop.2414" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="8.5.8-develop.2412" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="MimeKit" Version="4.14.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="Serilog" Version="4.3.1-dev-02406" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
    <PackageVersion Include="StackExchange.Redis" Version="2.10.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6" />
  </ItemGroup>
</Project>
