<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ZooApi.Application\ZooApi.Application.csproj" />
      <ProjectReference Include="..\ZooApi.Domain\ZooApi.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit.EntityFrameworkCore" />
      <PackageReference Include="MassTransit.RabbitMQ" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Serilog.Sinks.Console" />
      <PackageReference Include="Serilog.Sinks.File" />
      <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.9\Microsoft.AspNetCore.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
